// ImplementationOS — step definitions.
//
// Each step is one decision. `gate` returns whether Continue unlocks; `body`
// renders the screen; `attach` wires its controls (and calls the global
// `render` from app.js after mutating state). The attribute family steps are
// generated by `makeAttributeStep`. Depends on data.js, state.js, derive.js,
// util.js, and (at runtime) model.js's `Model` plus app.js's `render`.

const steps = [
  {
    id: "welcome", phase: "Start", nav: "Welcome", cta: "Begin setup",
    title: "Let's set up your APS pilot.",
    sub: "A guided, step-by-step build of the implementation model — one decision at a time. Nothing is final; you can go back at any point.",
    body: () => `
      <div class="welcome-art" aria-hidden="true">
        <i data-lucide="route"></i>
      </div>
      <ul class="welcome-list">
        <li><i data-lucide="target"></i><span>Start from the planning archetype, not the industry.</span></li>
        <li><i data-lucide="git-branch"></i><span>Try changes on a branch before committing them.</span></li>
        <li><i data-lucide="gauge"></i><span>Watch readiness build as you make each decision.</span></li>
      </ul>
    `,
  },
  {
    id: "scope", phase: "Scope", nav: "Planning objective",
    title: "What are you actually trying to accomplish?",
    sub: "Choose the planning level before describing the manufacturing archetype. Adjacent levels stay visible so the project boundary is explicit, but this demo currently supports APS and Detailed Scheduling only.",
    hint: "Select Advanced Planning & Detailed Scheduling to continue.",
    gate: () => state.scope === "aps-ds",
    body: () => `
      <div class="scope-grid">
        ${planningLevels.map((item, index) => `
          <button class="scope-card${item.available ? " available" : " inactive"}${state.scope === item.id ? " active" : ""}" type="button"
            ${item.available ? `data-scope="${item.id}"` : "disabled"}
            title="${item.available ? "Available in this demo" : "Visible for context; not active in this demo yet"}">
            <span class="scope-index">${String(index + 1).padStart(2, "0")}</span>
            <span class="scope-copy">
              <span class="scope-topline"><strong>${escapeHtml(item.level)}</strong><em>${escapeHtml(item.horizon)}</em></span>
              <span class="scope-question">${escapeHtml(item.question)}</span>
              <small>${escapeHtml(item.terms)}</small>
            </span>
            <i data-lucide="${item.available ? "arrow-right" : "lock-keyhole"}"></i>
          </button>
        `).join("")}
      </div>
    `,
    attach: (root) => {
      root.querySelector("[data-scope]")?.addEventListener("click", (event) => {
        state.scope = event.currentTarget.dataset.scope;
        render();
      });
    },
  },
  {
    id: "archetype", phase: "Characterize", nav: "Archetype",
    title: "What are you implementing?",
    sub: "Select every pattern that materially shapes the operation. The model will synthesize a planning backbone without erasing secondary behavior.",
    hint: "Choose at least one archetype to continue.",
    gate: () => state.archetypes?.length > 0,
    body: () => {
      const synthesis = archetypeSynthesis();
      return `
      <div class="archetype-synthesis${synthesis.count ? " populated" : ""}">
        <i data-lucide="layers-3"></i>
        <div><strong>${escapeHtml(synthesis.title)}</strong><p>${escapeHtml(synthesis.detail)}</p></div>
        <span>${synthesis.count} selected</span>
      </div>
      <div class="pick-grid" aria-label="Manufacturing archetypes">
        ${planningArchetypes
          .map(
            (a) => `
          <button class="pick-card${state.archetypes.includes(a.id) ? " active" : ""}" type="button" data-arch="${a.id}" data-mode="${a.mode}" aria-pressed="${state.archetypes.includes(a.id)}">
            <span class="pick-head"><i data-lucide="${archetypeIcons[a.id]}"></i><span class="pick-mode">${escapeHtml(modeProfiles[a.mode].label)}</span></span>
            <strong>${escapeHtml(a.name)}</strong>
            <p>${escapeHtml(a.core)}</p>
          </button>`
          )
          .join("")}
      </div>
    `;
    },
    attach: (root) => {
      root.querySelectorAll("[data-arch]").forEach((b) =>
        b.addEventListener("click", () => {
          const selected = new Set(state.archetypes);
          selected.has(b.dataset.arch) ? selected.delete(b.dataset.arch) : selected.add(b.dataset.arch);
          state.archetypes = [...selected];
          state.erp = mode().erp;
          render();
        })
      );
    },
  },
  {
    id: "industry", phase: "Characterize", nav: "Industry context",
    title: "Which industry context shapes the implementation?",
    sub: "Industry does not replace the operating archetype. It adds the regulatory, quality, traceability, safety, and terminology lens that makes the same production pattern behave differently.",
    hint: "Choose the primary industry context to continue.",
    gate: () => !!state.industry,
    body: () => {
      const selected = industry();
      return `
        ${selected ? `
          <div class="industry-synthesis">
            <i data-lucide="${selected.icon}"></i>
            <div><strong>${escapeHtml(selected.name)}</strong><p>${escapeHtml(selected.focus)}</p></div>
            <span>${escapeHtml(selected.compliance)}</span>
          </div>` : ""}
        <div class="industry-grid">
          ${industries.map((item) => `
            <button class="industry-card${state.industry === item.id ? " active" : ""}" type="button" data-industry="${item.id}" aria-pressed="${state.industry === item.id}">
              <i data-lucide="${item.icon}"></i>
              <span><small>${escapeHtml(item.group)}</small><strong>${escapeHtml(item.name)}</strong><em>${escapeHtml(item.focus)}</em></span>
            </button>
          `).join("")}
        </div>
      `;
    },
    attach: (root) => {
      root.querySelectorAll("[data-industry]").forEach((button) => button.addEventListener("click", () => {
        state.industry = button.dataset.industry;
        render();
      }));
    },
  },
  {
    id: "dialect", phase: "Characterize", nav: "Dialect",
    title: "Confirm the planning dialect.",
    sub: "The synthesized operating backbone recommends the planning language. Secondary archetypes remain overlays; override the ERP dialect if the client's system differs.",
    body: () => `
      <div class="derive">
        <div class="derive-chain">
          <span class="chain-node industry-node">${escapeHtml(industry()?.name || "Industry not set")}</span>
          <i data-lucide="plus"></i>
          <span class="chain-node">${escapeHtml(archetypeSynthesis().count === 1 ? archetypeSynthesis().title : `${archetypeSynthesis().count} reconciled patterns`)}</span>
          <i data-lucide="arrow-right"></i>
          <span class="chain-node accent">${escapeHtml(mode().label)}</span>
          <i data-lucide="arrow-right"></i>
          <span class="chain-node">${escapeHtml(profile().badge)}</span>
        </div>
        <p class="derive-note">${escapeHtml(mode().note)} ${industry() ? `Industry lens: ${escapeHtml(industry().focus)}` : ""}</p>
        <label class="field big-field">
          <span>ERP dialect</span>
          <select id="erpSelect">
            ${Object.entries(profiles).map(([id, item]) => `<option value="${escapeHtml(id)}">${escapeHtml(item.name)}</option>`).join("")}
          </select>
        </label>
        <div class="derive-chain hierarchy-chain" aria-label="ERP organization hierarchy">
          ${profile().hierarchy.map((term, index) => `${index ? '<i data-lucide="arrow-right"></i>' : ""}<span class="chain-node">${escapeHtml(term)}</span>`).join("")}
        </div>
        <div class="vocab-line">
          <span>You'll plan</span>
          <strong>${escapeHtml(profile().order)}s</strong>
          <em>against</em>
          <strong>${escapeHtml(profile().route)}s</strong>
          <em>at</em>
          <strong>${escapeHtml(profile().facility)}</strong>
          <em>using</em>
          <strong>${escapeHtml(profile().resource)}s</strong>
        </div>
      </div>
    `,
    attach: (root) => {
      const sel = root.querySelector("#erpSelect");
      sel.value = state.erp;
      sel.addEventListener("change", (e) => { state.erp = e.target.value; render(); });
    },
  },
  {
    id: "migration", phase: "Characterize", nav: "Migration",
    title: "Is an S/4 migration on the roadmap?",
    sub: "If a migration is coming, the design avoids one-off mappings — and it shows up as a standing risk on your readiness.",
    hint: "Pick one to continue.",
    gate: () => state.migration !== null,
    body: () => `
      <div class="choice-grid two">
        ${choiceTile("yes", state.migration === true, "calendar-clock", "Yes, it's coming", "Design for portability; flag the risk")}
        ${choiceTile("no", state.migration === false, "circle-off", "No, not planned", "Optimize for the current system")}
      </div>
    `,
    attach: (root) => bindChoices(root, (v) => { state.migration = v === "yes"; render(); }),
  },
  {
    id: "calendar", phase: () => organizationTerm(), nav: "Calendars & capacity",
    title: "Where does available capacity really come from?",
    sub: () => `${calendarProfile().base} defines broad working days; ${calendarProfile().resource} determines whether a specific ${profile().resource.toLowerCase()} can actually run. Capture both layers before APS interprets an open day as usable capacity.`,
    hint: "Complete all four calendar and capacity dimensions to continue.",
    gate: () => !!(state.calendar?.layering && state.calendar?.pattern && state.calendar?.exceptions && state.calendar?.modifiersConfirmed),
    body: () => {
      const cal = state.calendar || initialState.calendar;
      const terms = calendarProfile();
      const modifier = (value, icon, title, sub) => choiceTile(value, cal.modifiers.includes(value), icon, title, sub).replace("data-choice", "data-calendar-modifier");
      return `
        <div class="capacity-profile">
          <section class="capacity-dimension">
            <div class="dimension-heading"><span>01</span><div><strong>Availability layers</strong><small>Where open time is defined</small></div></div>
            <div class="choice-grid three compact" data-calendar-group="layering">
              ${choiceTile("facility-only", cal.layering === "facility-only", "calendar-days", terms.base, `Only the ${profile().facility.toLowerCase()}-level calendar is available`)}
              ${choiceTile("resource-only", cal.layering === "resource-only", "cpu", terms.resource, `Availability is maintained directly on each ${profile().resource.toLowerCase()}`)}
              ${choiceTile("layered", cal.layering === "layered", "layers-3", "Layered calendars", `${terms.base} plus ${terms.resource.toLowerCase()} overrides`)}
            </div>
          </section>
          <section class="capacity-dimension">
            <div class="dimension-heading"><span>02</span><div><strong>Working-time pattern</strong><small>${escapeHtml(terms.pattern)}</small></div></div>
            <div class="choice-grid three compact" data-calendar-group="pattern">
              ${choiceTile("single-shift", cal.pattern === "single-shift", "sun", "Single shift", "One recurring work interval per working day")}
              ${choiceTile("multi-shift", cal.pattern === "multi-shift", "clock-3", "Multiple shifts", "Two or more named intervals share the day")}
              ${choiceTile("variable", cal.pattern === "variable", "calendar-range", "Variable / rotating", "Patterns change by day, week, crew, or activity")}
            </div>
          </section>
          <section class="capacity-dimension">
            <div class="dimension-heading"><span>03</span><div><strong>Exceptions</strong><small>${escapeHtml(terms.exception)}</small></div></div>
            <div class="choice-grid three compact" data-calendar-group="exceptions">
              ${choiceTile("base-only", cal.exceptions === "base-only", "calendar-off", "Base-calendar only", "Holidays and closures apply broadly")}
              ${choiceTile("resource-overrides", cal.exceptions === "resource-overrides", "wrench", "Resource overrides", "Maintenance and local downtime override open days")}
              ${choiceTile("multi-activity", cal.exceptions === "multi-activity", "calendar-cog", "Activity-specific", "Production, service, logistics, or other availability differs")}
            </div>
          </section>
          <section class="capacity-dimension">
            <div class="dimension-heading"><span>04</span><div><strong>Capacity modifiers</strong><small>Select all supplied by the ERP</small></div></div>
            <div class="choice-grid compact capacity-modifiers">
              ${modifier("units", "copy", terms.units, "Number of parallel people, machines, or capacity units")}
              ${modifier("efficiency", "gauge", terms.efficiency, "Usable percentage or performance factor")}
              ${modifier("category", "tags", terms.category, "Machine, labor, setup, processing, or activity type")}
              ${choiceTile("none", cal.modifiersConfirmed && cal.modifiers.length === 0, "circle-slash-2", "None supplied", "Use working time without additional modifiers").replace("data-choice", "data-calendar-modifier-none")}
            </div>
          </section>
        </div>
      `;
    },
    attach: (root) => {
      root.querySelectorAll("[data-calendar-group]").forEach((group) => {
        group.querySelectorAll("[data-choice]").forEach((button) => button.addEventListener("click", () => {
          state.calendar[group.dataset.calendarGroup] = button.dataset.choice;
          render();
        }));
      });
      root.querySelectorAll("[data-calendar-modifier]").forEach((button) => button.addEventListener("click", () => {
        const value = button.dataset.calendarModifier;
        const selected = new Set(state.calendar.modifiers);
        selected.has(value) ? selected.delete(value) : selected.add(value);
        state.calendar.modifiers = [...selected];
        state.calendar.modifiersConfirmed = true;
        render();
      }));
      root.querySelector("[data-calendar-modifier-none]")?.addEventListener("click", () => {
        state.calendar.modifiers = [];
        state.calendar.modifiersConfirmed = true;
        render();
      });
    },
  },
  {
    id: "constraint", phase: () => organizationTerm(), nav: "Constraint view",
    title: "What is currently known about the constraint?",
    sub: "Capture the customer's view as a hypothesis, not as planning truth. The limiting constraint may be unknown or shift by horizon, product mix, campaign, and scenario.",
    hint: "Choose the best current description. It can be refined when data and scenarios reveal more.",
    gate: () => !!state.constraint,
    body: () => `
      <div class="choice-grid three">
        ${choiceTile("unknown", state.constraint === "unknown", "circle-help", "Not known yet", "Let data profiling and scenario runs surface likely constraints")}
        ${choiceTile("shifting", state.constraint === "shifting", "shuffle", "Shifting constraint", "Changes with horizon, product mix, campaign, or operating conditions")}
        ${choiceTile("equipment-family", state.constraint === "equipment-family", "cog", "Equipment family", "Customer-observed capacity pattern; representative resources will illustrate it")}
        ${choiceTile("shared-stage", state.constraint === "shared-stage", "workflow", "Shared processing stage", "A shared stage may constrain multiple products or campaigns")}
        ${choiceTile("quality-release", state.constraint === "quality-release", "microscope", "Quality release", "Inspection, testing, or release capacity may gate the schedule")}
      </div>
    `,
    attach: (root) => bindChoices(root, (v) => { state.constraint = v; render(); }),
  },
  {
    id: "areas", phase: "Model", nav: "Department taxonomy",
    title: () => `Which ${profile().area.toLowerCase()} types belong in the representative model?`,
    sub: "Select semantic categories, not customer department names. The generator will create synthetic examples that preserve these roles and relationships.",
    hint: "Select at least one department type to continue.",
    gate: () => state.departmentTypes?.length > 0,
    body: () => `
      <div class="taxonomy-grid">
        ${departmentTaxonomy.map((item) => `
          <button class="taxonomy-card${state.departmentTypes.includes(item.id) ? " active" : ""}" type="button" data-department-type="${item.id}" aria-pressed="${state.departmentTypes.includes(item.id)}">
            <i data-lucide="${item.icon}"></i>
            <span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.note)}</small></span>
          </button>
        `).join("")}
      </div>
      <p class="representative-note"><i data-lucide="sparkles"></i> ${state.departmentTypes.length || "No"} department type${state.departmentTypes.length === 1 ? "" : "s"} will seed representative records.</p>
    `,
    attach: (root) => {
      root.querySelectorAll("[data-department-type]").forEach((button) => button.addEventListener("click", () => {
        const selected = new Set(state.departmentTypes);
        selected.has(button.dataset.departmentType) ? selected.delete(button.dataset.departmentType) : selected.add(button.dataset.departmentType);
        state.departmentTypes = [...selected];
        render();
      }));
    },
  },
  {
    id: "workcenters", phase: "Model", nav: "Resource taxonomy",
    title: () => `Which ${profile().resource.toLowerCase()} types should the generator represent?`,
    sub: "Choose capacity-object categories, not named machines or people. Synthetic examples will be linked to compatible department types automatically.",
    hint: "Select at least one resource type to continue.",
    gate: () => state.resourceTypes?.length > 0,
    body: () => `
      <div class="taxonomy-grid">
        ${resourceTaxonomy.map((item) => `
          <button class="taxonomy-card${state.resourceTypes.includes(item.id) ? " active" : ""}" type="button" data-resource-type="${item.id}" aria-pressed="${state.resourceTypes.includes(item.id)}">
            <i data-lucide="${item.icon}"></i>
            <span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.note)}</small></span>
          </button>
        `).join("")}
      </div>
      <p class="representative-note"><i data-lucide="sparkles"></i> ${state.resourceTypes.length || "No"} resource type${state.resourceTypes.length === 1 ? "" : "s"} will seed representative records.</p>
    `,
    attach: (root) => {
      root.querySelectorAll("[data-resource-type]").forEach((button) => button.addEventListener("click", () => {
        const selected = new Set(state.resourceTypes);
        selected.has(button.dataset.resourceType) ? selected.delete(button.dataset.resourceType) : selected.add(button.dataset.resourceType);
        state.resourceTypes = [...selected];
        render();
      }));
    },
  },
  ...attributeConcepts.map(makeAttributeStep),
  {
    id: "transitions", phase: "Model", nav: "Setup & cleaning",
    title: "How do setups, changeovers, and cleaning behave?",
    sub: () => `Between runs the line loses time to setups, changeovers, and cleans. APS must know what inserts them, whether they block the ${profile().resource.toLowerCase()}, and what they are keyed to — your ${itemTerm()} attributes or SKU codes.`,
    hint: "Pick the transition types, at least one trigger, the concurrency, and what drives them.",
    gate: () => transitionsConfigured(),
    body: () => {
      const t = state.transitions || initialState.transitions;
      const typeChip = (it) => choiceTile(it.id, t.types.includes(it.id), it.icon, it.name, it.note).replace("data-choice", "data-transition-type");
      const triggerChip = (it) => choiceTile(it.id, t.triggers.includes(it.id), it.icon, it.name, it.note).replace("data-choice", "data-transition-trigger");
      const driverChip = (it) => choiceTile(it.id, t.drivers.includes(it.id), it.icon, it.name, it.note).replace("data-choice", "data-transition-driver");
      const selectedAttrs = allSelectedAttributes();
      const typeNames = transitionTypes.filter((x) => t.types.includes(x.id)).map((x) => x.name);
      const concLabel = transitionConcurrency.find((x) => x.id === t.concurrency)?.name;
      const synth = t.types.length ? `${typeNames.join(", ")}${concLabel ? ` · ${concLabel}` : ""}${t.triggers.length ? ` · ${t.triggers.length} trigger rule${t.triggers.length === 1 ? "" : "s"}` : ""}` : "";
      return `
        ${synth ? `<div class="execution-synthesis"><i data-lucide="repeat"></i><span>${escapeHtml(synth)}</span></div>` : ""}
        <div class="bom-profile">
          <section class="bom-dimension">
            <div class="dimension-heading"><span>01</span><div><strong>Transition types</strong><small>Select every kind the line performs</small></div></div>
            <div class="choice-grid three compact">
              ${transitionTypes.map(typeChip).join("")}
            </div>
          </section>
          <section class="bom-dimension">
            <div class="dimension-heading"><span>02</span><div><strong>Trigger basis</strong><small>What inserts the transition — select all that apply</small></div></div>
            <div class="choice-grid three compact">
              ${transitionTriggers.map(triggerChip).join("")}
            </div>
          </section>
          <section class="bom-dimension">
            <div class="dimension-heading"><span>03</span><div><strong>Concurrency</strong><small>Whether it occupies the resource</small></div></div>
            <div class="choice-grid three compact" data-transition-group="concurrency">
              ${transitionConcurrency.map((it) => choiceTile(it.id, t.concurrency === it.id, it.icon, it.name, it.note)).join("")}
            </div>
          </section>
          <section class="bom-dimension">
            <div class="dimension-heading"><span>04</span><div><strong>What drives it</strong><small>How the transition is identified — select all that apply</small></div></div>
            <div class="choice-grid three compact">
              ${transitionDrivers.map(driverChip).join("")}
            </div>
            ${t.drivers.includes("attribute") ? `
              <div class="transition-attr-link">
                ${selectedAttrs.length ? `
                  <p class="attr-suggested-label">Attributes that drive transitions</p>
                  <div class="attr-chips">${selectedAttrs.map((name) => `<button class="attr-chip${t.driverAttributes.includes(name) ? " active" : ""}" type="button" data-transition-attr="${escapeHtml(name)}">${escapeHtml(name)}</button>`).join("")}</div>`
                  : `<p class="representative-note"><i data-lucide="info"></i> No item attributes were selected earlier — define them in the attribute steps, or drive transitions by SKU instead.</p>`}
              </div>` : ""}
          </section>
        </div>
      `;
    },
    attach: (root) => {
      const t = state.transitions;
      const toggle = (arr, value) => {
        const set = new Set(arr);
        set.has(value) ? set.delete(value) : set.add(value);
        return [...set];
      };
      root.querySelectorAll("[data-transition-type]").forEach((button) => button.addEventListener("click", () => {
        t.types = toggle(t.types, button.dataset.transitionType);
        render();
      }));
      root.querySelectorAll("[data-transition-trigger]").forEach((button) => button.addEventListener("click", () => {
        t.triggers = toggle(t.triggers, button.dataset.transitionTrigger);
        render();
      }));
      root.querySelectorAll('[data-transition-group="concurrency"] [data-choice]').forEach((button) => button.addEventListener("click", () => {
        t.concurrency = button.dataset.choice;
        render();
      }));
      root.querySelectorAll("[data-transition-driver]").forEach((button) => button.addEventListener("click", () => {
        t.drivers = toggle(t.drivers, button.dataset.transitionDriver);
        if (!t.drivers.includes("attribute")) t.driverAttributes = [];
        render();
      }));
      root.querySelectorAll("[data-transition-attr]").forEach((button) => button.addEventListener("click", () => {
        t.driverAttributes = toggle(t.driverAttributes, button.dataset.transitionAttr);
        render();
      }));
    },
  },
  {
    id: "bom", phase: "Model", nav: "BOM profile",
    title: "How does the product structure reach planning?",
    sub: () => `Characterize the ${profile().route.toLowerCase()} and component model across four independent dimensions. APS should preserve what matters without assuming every ERP sends a clean master BOM.`,
    hint: "Complete all four BOM dimensions to continue.",
    gate: () => !!(state.bom?.structure && state.bom?.featuresConfirmed && state.bom?.consumption && state.bom?.source),
    body: () => {
      const bom = state.bom || initialState.bom;
      const feature = (value, icon, title, sub) => choiceTile(value, bom.features.includes(value), icon, title, sub).replace("data-choice", "data-bom-feature");
      return `
        <div class="bom-profile">
          <section class="bom-dimension">
            <div class="dimension-heading"><span>01</span><div><strong>Structure</strong><small>How components are represented</small></div></div>
            <div class="choice-grid three compact" data-bom-group="structure">
              ${choiceTile("multi-level", bom.structure === "multi-level", "network", "Multi-level", "Preserve assemblies and lower-level dependencies")}
              ${choiceTile("single-level", bom.structure === "single-level", "list-tree", "Collapsed single level", "Planning receives an exploded component list")}
              ${choiceTile("recipe-formula", bom.structure === "recipe-formula", "flask-conical", "Recipe / formula", "Ingredients, quantities, phases, or process instructions")}
            </div>
          </section>
          <section class="bom-dimension">
            <div class="dimension-heading"><span>02</span><div><strong>Special behavior</strong><small>Select all that occur</small></div></div>
            <div class="choice-grid compact bom-features">
              ${feature("phantoms", "combine", "Phantom assemblies", "Logical groupings exploded without their own order")}
              ${feature("recursion", "repeat-2", "Recursion / loops", "Rework, co-products, or structures that revisit themselves")}
              ${feature("potency", "test-tube-2", "Lot potency / assay", "Required quantity varies by lot strength or concentration")}
              ${choiceTile("none", bom.featuresConfirmed && bom.features.length === 0, "circle-slash-2", "None identified", "Explicitly confirm no special behavior").replace("data-choice", "data-bom-feature-none")}
            </div>
          </section>
          <section class="bom-dimension">
            <div class="dimension-heading"><span>03</span><div><strong>Consumption linkage</strong><small>Where demand is attached</small></div></div>
            <div class="choice-grid three compact" data-bom-group="consumption">
              ${choiceTile("operation", bom.consumption === "operation", "git-commit-horizontal", "Operation-linked", "Each component points to a consuming operation or phase")}
              ${choiceTile("order", bom.consumption === "order", "package", "Order-level", "Components are consumed without an operation assignment")}
              ${choiceTile("mixed", bom.consumption === "mixed", "split", "Mixed", "Operation-linked and order-level consumption coexist")}
            </div>
          </section>
          <section class="bom-dimension">
            <div class="dimension-heading"><span>04</span><div><strong>Integration grain</strong><small>What the ERP actually sends</small></div></div>
            <div class="choice-grid three compact" data-bom-group="source">
              ${choiceTile("master", bom.source === "master", "library", "Master BOM / recipe", "Versioned product structure from master data")}
              ${choiceTile("order-specific", bom.source === "order-specific", "clipboard-list", "Order BOM", "Copied or changed structure attached to the order")}
              ${choiceTile("allocation", bom.source === "allocation", "boxes", "Allocation / reservation", "Actual reserved materials, batches, or supply assignments")}
              ${choiceTile("hybrid", bom.source === "hybrid", "layers-3", "Hybrid", "Master structure plus order and reservation deltas")}
            </div>
          </section>
        </div>
      `;
    },
    attach: (root) => {
      root.querySelectorAll("[data-bom-group]").forEach((group) => {
        group.querySelectorAll("[data-choice]").forEach((button) => button.addEventListener("click", () => {
          state.bom[group.dataset.bomGroup] = button.dataset.choice;
          render();
        }));
      });
      root.querySelectorAll("[data-bom-feature]").forEach((button) => button.addEventListener("click", () => {
        const value = button.dataset.bomFeature;
        const selected = new Set(state.bom.features);
        selected.has(value) ? selected.delete(value) : selected.add(value);
        state.bom.features = [...selected];
        state.bom.featuresConfirmed = true;
        render();
      }));
      root.querySelector("[data-bom-feature-none]")?.addEventListener("click", () => {
        state.bom.features = [];
        state.bom.featuresConfirmed = true;
        render();
      });
    },
  },
  {
    id: "execution", phase: "Model", nav: "Execution feedback",
    title: "How does actual execution return to planning?",
    sub: () => `Configure the feedback contract separately from the ${profile().route.toLowerCase()}. MES events and ${profile().badge} confirmations may describe the same work at different levels and times.`,
    hint: "Complete the source, reporting level, event, and quantity configuration.",
    gate: () => !!(state.execution?.source && state.execution?.levels?.length && state.execution?.events?.length && state.execution?.quantitiesConfirmed),
    body: () => {
      const execution = state.execution || initialState.execution;
      const signal = (group, value, icon, title, sub) => {
        const attribute = { levels: "level", events: "event", quantities: "quantity" }[group];
        return choiceTile(value, execution[group].includes(value), icon, title, sub).replace("data-choice", `data-execution-${attribute}`);
      };
      const sourceNote = {
        erp: `${profile().badge} is the execution system of record and sends official confirmations.`,
        mes: `MES sends detailed execution events; ${profile().badge} remains planning context rather than the confirmation source.`,
        hybrid: `MES provides event detail while ${profile().badge} provides official postings; identifiers and duplicate-event rules must reconcile both.`,
      }[execution.source];
      return `
        ${sourceNote ? `<div class="execution-synthesis"><i data-lucide="refresh-cw"></i><span>${escapeHtml(sourceNote)}</span></div>` : ""}
        <div class="execution-profile">
          <section class="execution-dimension">
            <div class="dimension-heading"><span>01</span><div><strong>System of record</strong><small>Who publishes execution truth</small></div></div>
            <div class="choice-grid three compact" data-execution-group="source">
              ${choiceTile("erp", execution.source === "erp", "database", `${profile().badge} confirmations`, "ERP owns starts, finishes, and quantities")}
              ${choiceTile("mes", execution.source === "mes", "monitor-cog", "MES execution events", "MES owns detailed shop-floor feedback")}
              ${choiceTile("hybrid", execution.source === "hybrid", "git-merge", "Hybrid MES + ERP", "MES detail reconciled to official ERP postings")}
            </div>
          </section>
          <section class="execution-dimension">
            <div class="dimension-heading"><span>02</span><div><strong>Reporting level</strong><small>Select every level received</small></div></div>
            <div class="choice-grid three compact">
              ${signal("levels", "order-batch", "clipboard-list", `${profile().order} / batch`, "One confirmation summarizes the whole order or batch")}
              ${signal("levels", "operation-step", "list-checks", "Operation / step", "Feedback is attached to a routing operation or instruction step")}
              ${signal("levels", "phase", "split", "Phase", "Process phases publish their own execution status")}
            </div>
          </section>
          <section class="execution-dimension">
            <div class="dimension-heading"><span>03</span><div><strong>Lifecycle events</strong><small>Select every event received</small></div></div>
            <div class="choice-grid three compact">
              ${signal("events", "start", "play", "Start", "Actual start of an order, operation, step, or phase")}
              ${signal("events", "end", "square-check-big", "End / completion", "Final completion or technically complete status")}
              ${signal("events", "partial", "circle-dot-dashed", "Partial / progress", "Incremental confirmation before final completion")}
            </div>
          </section>
          <section class="execution-dimension">
            <div class="dimension-heading"><span>04</span><div><strong>Quantity outcomes</strong><small>Select every quantity received</small></div></div>
            <div class="choice-grid compact execution-signals">
              ${signal("quantities", "yield", "badge-check", "Yield / good quantity", "Accepted production quantity or process yield")}
              ${signal("quantities", "scrap", "trash-2", "Scrap / reject", "Rejected quantity and optional reason code")}
              ${signal("quantities", "rework", "rotate-ccw", "Rework", "Quantity routed back into correction or reprocessing")}
              ${signal("quantities", "consumption", "package-minus", "Material consumption", "Actual component, ingredient, lot, or container usage")}
              ${choiceTile("status-only", execution.quantitiesConfirmed && execution.quantities.length === 0, "activity", "Status only", "No execution quantities are supplied").replace("data-choice", "data-execution-quantity-none")}
            </div>
          </section>
        </div>
      `;
    },
    attach: (root) => {
      root.querySelectorAll("[data-execution-group]").forEach((group) => {
        group.querySelectorAll("[data-choice]").forEach((button) => button.addEventListener("click", () => {
          state.execution[group.dataset.executionGroup] = button.dataset.choice;
          render();
        }));
      });
      ["level", "event", "quantity"].forEach((group) => {
        root.querySelectorAll(`[data-execution-${group}]`).forEach((button) => button.addEventListener("click", () => {
          const key = { level: "levels", event: "events", quantity: "quantities" }[group];
          const selected = new Set(state.execution[key]);
          selected.has(button.dataset[`execution${group[0].toUpperCase()}${group.slice(1)}`])
            ? selected.delete(button.dataset[`execution${group[0].toUpperCase()}${group.slice(1)}`])
            : selected.add(button.dataset[`execution${group[0].toUpperCase()}${group.slice(1)}`]);
          state.execution[key] = [...selected];
          if (group === "quantity") state.execution.quantitiesConfirmed = true;
          render();
        }));
      });
      root.querySelector("[data-execution-quantity-none]")?.addEventListener("click", () => {
        state.execution.quantities = [];
        state.execution.quantitiesConfirmed = true;
        render();
      });
    },
  },
  {
    id: "variant", phase: "Model", nav: "Try a variant",
    title: "Want to try a variant before committing?",
    sub: "Branching lets you explore a taxonomy change in isolation. The example uses synthetic Packaging and Finished-Goods records, never customer master data.",
    hint: "Try it or skip to continue.",
    gate: () => state.variant === "kept" || state.variant === "reverted" || state.variant === "skipped",
    body: () => {
      if (state.variant === "active") {
        const { entries } = Model.diff("variant-finished-goods");
        return `
          <div class="variant-live">
            <p class="variant-flag"><i data-lucide="git-branch"></i> On branch <strong>variant-finished-goods</strong> — ${entries.length} change${entries.length === 1 ? "" : "s"}</p>
            <div class="diff-list">
              ${entries
                .map(
                  (e) => `
                <div class="diff-item">
                  <span class="diff-kind ${e.kind}">${e.kind}</span>
                  <strong>${escapeHtml(e.name)}</strong>
                  ${e.changes ? e.changes.map((c) => `<span class="diff-pair"><em>${escapeHtml(c.field)}</em> ${escapeHtml(String(c.before ?? "—"))} → <b>${escapeHtml(String(c.after ?? "—"))}</b></span>`).join("") : ""}
                </div>`
                )
                .join("") || '<p class="muted">No changes recorded.</p>'}
            </div>
            <div class="variant-actions">
              <button class="cta solid" id="keepVariant" type="button"><i data-lucide="git-merge"></i><span>Keep variant</span></button>
              <button class="ghost-btn" id="revertVariant" type="button"><i data-lucide="undo-2"></i><span>Revert</span></button>
            </div>
          </div>
        `;
      }
      if (state.variant === "kept" || state.variant === "reverted") {
        const kept = state.variant === "kept";
        return `
          <div class="variant-outcome ${kept ? "kept" : "reverted"}">
            <i data-lucide="${kept ? "git-merge" : "undo-2"}"></i>
            <strong>${kept ? "Variant kept" : "Variant reverted"}</strong>
            <p>${kept ? "Packaging is now Finished Goods on the baseline — the merge is recorded as a governed decision." : "The baseline is unchanged. The branch was discarded."}</p>
          </div>
        `;
      }
      return `
        <div class="choice-grid two">
          ${choiceTile("try", false, "git-branch", "Try a variant", "Fork, change, review the diff")}
          ${choiceTile("skip", state.variant === "skipped", "arrow-right", "Skip for now", "Keep the baseline as-is")}
        </div>
      `;
    },
    attach: (root) => {
      root.querySelector("#keepVariant")?.addEventListener("click", () => {
        Model.merge("variant-finished-goods", { approver: "You", rationale: "Adopted Finished-Goods naming for go-live." });
        state.variant = "kept";
        render();
      });
      root.querySelector("#revertVariant")?.addEventListener("click", () => {
        Model.discardBranch("variant-finished-goods");
        state.variant = "reverted";
        render();
      });
      bindChoices(root, (v) => {
        if (v === "skip") { state.variant = "skipped"; render(); return; }
        if (v === "try") {
          if (Model.branch() !== "main") Model.checkout("main");
          Model.createBranch("variant-finished-goods");
          Model.commit({ label: "Renamed Packaging to Finished Goods on a variant branch.", ops: [{ op: "update", id: "packaging", props: { name: "Finished Goods", renamed: true } }] });
          state.variant = "active";
          render();
        }
      });
    },
  },
  {
    id: "demo", phase: "Validate", nav: "Representative scenario",
    title: "Validate with a synthetic scheduling scenario.",
    sub: () => `A generated rush ${profile().order.toLowerCase()} needs representative packaging capacity. The scenario tests the configured logic without asking for customer orders or resources.`,
    hint: "Schedule the order to continue.",
    gate: () => !!state.demo,
    body: () => {
      const lanes = [
        ["wc-pack-3", "Packaging Line 3", "Preferred line, but calendar data is incomplete."],
        ["wc-pack-2", "Packaging Line 2", "Alternate line with available capacity."],
        ["wc-qc-1", "QC Release Bench", "Wrong capability for packaging operations."],
      ];
      return `
        ${state.demo ? `<div class="demo-result"><strong>${state.demo.score}% — training scored</strong><p>${escapeHtml(state.demo.note)}</p></div>` : ""}
        <div class="lane-list">
          ${lanes
            .map(
              ([id, name, note]) => `
            <button class="lane${state.demo?.laneId === id ? " picked" : ""}" type="button" data-lane="${id}">
              <strong>${escapeHtml(name)}</strong>
              <span>${escapeHtml(note)}</span>
            </button>`
            )
            .join("")}
        </div>
      `;
    },
    attach: (root) => {
      root.querySelectorAll("[data-lane]").forEach((b) =>
        b.addEventListener("click", () => { scoreDemo(b.dataset.lane); })
      );
    },
  },
  {
    id: "readiness", phase: "Validate", nav: "Readiness",
    title: "Your readiness so far.",
    sub: "Computed from every decision you've made — model completeness, the data issue, and the demo evidence.",
    body: () => {
      const r = readiness();
      const attrFamiliesConfirmed = Object.values(state.attr || {}).filter((slot) => slot?.confirmed).length;
      const attrPicksTotal = Object.values(state.attr || {}).reduce((sum, slot) => sum + (slot?.picks?.length || 0), 0);
      const rows = [
        ["Planning objective", state.scope ? "done" : "open", state.scope === "aps-ds" ? "Advanced Planning & Detailed Scheduling" : "Not selected"],
        ["Operating archetypes", state.archetypes?.length ? "done" : "open", state.archetypes?.length ? archetypeSynthesis().title : "Not characterized"],
        ["Industry context", state.industry ? "done" : "open", industry()?.name || "Not selected"],
        ["Department taxonomy", state.departmentTypes?.length ? "done" : "open", state.departmentTypes?.length ? `${state.departmentTypes.length} semantic types selected` : "Not configured"],
        ["Calendars & capacity", state.calendar?.layering ? "done" : "open", state.calendar?.layering ? `${calendarProfile().base} · ${state.calendar.pattern} · ${state.calendar.exceptions}` : "Not characterized"],
        ["Resource taxonomy", state.resourceTypes?.length ? "done" : "open", state.resourceTypes?.length ? `${state.resourceTypes.length} capacity-object types selected` : "Not configured"],
        ["Item attributes", attrFamiliesConfirmed ? "done" : "open", attrFamiliesConfirmed ? `${attrPicksTotal} attribute${attrPicksTotal === 1 ? "" : "s"} across ${attrFamiliesConfirmed} famil${attrFamiliesConfirmed === 1 ? "y" : "ies"}` : "Not characterized"],
        ["Setup & changeovers", transitionsConfigured() ? "done" : "open", state.transitions?.types?.length ? `${transitionTypes.filter((x) => state.transitions.types.includes(x.id)).map((x) => x.name).join(", ")} · ${state.transitions.triggers.length} trigger${state.transitions.triggers.length === 1 ? "" : "s"}` : "Not characterized"],
        ["BOM profile", state.bom?.source ? "done" : "open", state.bom?.source ? `${state.bom.structure} · ${state.bom.consumption} · ${state.bom.source}` : "Not characterized"],
        ["Execution feedback", state.execution?.source ? "done" : "open", state.execution?.source ? `${executionSourceLabel()} · ${state.execution.events.join(", ")}` : "Not configured"],
        ["Representative evidence", state.demo ? "done" : "open", state.demo ? `${state.demo.score}% scenario score` : "Pending"],
        ["Migration risk", "info", state.migration ? "S/4 migration on roadmap" : "No migration planned"],
      ];
      return `
        <div class="readiness-hero">
          <div class="ring" style="--p:${r}">
            <span>${r}<small>%</small></span>
          </div>
          <div class="readiness-lines">
            ${rows
              .map(
                ([label, st, detail]) => `
              <div class="rline">
                <i data-lucide="${st === "done" ? "circle-check" : st === "info" ? "info" : "circle-dashed"}" class="ic-${st}"></i>
                <strong>${escapeHtml(label)}</strong>
                <span>${escapeHtml(detail)}</span>
              </div>`
              )
              .join("")}
          </div>
        </div>
      `;
    },
  },
  {
    id: "handoff", phase: "Handoff", nav: "Handoff", cta: "Finish setup",
    title: "Hand off to the support organization.",
    sub: "The journey ends where support begins. This exports the model, decisions, and evidence — managed services are out of scope.",
    body: () => {
      const decisions = Model.nodesOfType("decision");
      const generated = representativeData();
      const attrPicksTotal = Object.values(state.attr || {}).reduce((sum, slot) => sum + (slot?.picks?.length || 0), 0);
      return `
        <div class="summary-grid">
          <div class="summary-card"><span>Objective</span><strong>${state.scope === "aps-ds" ? "APS / Detailed Scheduling" : "Pending"}</strong><small>hours-to-weeks planning horizon</small></div>
          <div class="summary-card"><span>Industry</span><strong>${industry() ? escapeHtml(industry().name) : "Pending"}</strong><small>${industry() ? escapeHtml(industry().compliance) : "context not selected"}</small></div>
          <div class="summary-card"><span>Representative data</span><strong>${generated.departments.length} departments · ${generated.resources.length} resources</strong><small>synthetic and replaceable</small></div>
          <div class="summary-card"><span>Item attributes</span><strong>${attrPicksTotal} captured</strong><small>${escapeHtml(attributeProfile().family)}</small></div>
          <div class="summary-card"><span>Setup & cleaning</span><strong>${state.transitions?.types?.length ? `${state.transitions.types.length} transition type${state.transitions.types.length === 1 ? "" : "s"}` : "Pending"}</strong><small>${state.transitions?.concurrency ? escapeHtml(transitionConcurrency.find((x) => x.id === state.transitions.concurrency)?.name || "") : "concurrency not set"}</small></div>
          <div class="summary-card"><span>BOM</span><strong>${state.bom?.structure ? escapeHtml(state.bom.structure) : "Pending"}</strong><small>${state.bom?.source ? escapeHtml(state.bom.source) : "integration grain not set"}</small></div>
          <div class="summary-card"><span>Capacity</span><strong>${state.calendar?.layering ? escapeHtml(state.calendar.layering) : "Pending"}</strong><small>${state.calendar?.pattern ? escapeHtml(state.calendar.pattern) : "calendar pattern not set"}</small></div>
          <div class="summary-card"><span>Execution</span><strong>${escapeHtml(executionSourceLabel())}</strong><small>${state.execution?.events?.length ? escapeHtml(state.execution.events.join(" · ")) : "feedback events not set"}</small></div>
          <div class="summary-card"><span>Decisions</span><strong>${decisions.length} governed</strong><small>${decisions.length ? "merge history travels with handoff" : "no branch merges"}</small></div>
          <div class="summary-card"><span>Evidence</span><strong>${state.demo ? state.demo.score + "% training" : "Pending"}</strong><small>${state.demo ? "seeds the support runbook" : "no scored scenario"}</small></div>
          <div class="summary-card"><span>Readiness</span><strong>${readiness()}%</strong><small>at handoff</small></div>
        </div>
        <section class="generated-preview" aria-label="Generated representative dataset">
          <div class="generated-heading"><div><span>Generated representative dataset</span><strong>${escapeHtml(generated.organization.name)}</strong></div><em>synthetic</em></div>
          <div class="generated-columns">
            <div><span>${escapeHtml(profile().area)} examples</span>${generated.departments.map((item) => `<code>${escapeHtml(item.id)}</code><small>${escapeHtml(item.name)}</small>`).join("") || "<small>No department types selected</small>"}</div>
            <div><span>${escapeHtml(profile().resource)} examples</span>${generated.resources.map((item) => `<code>${escapeHtml(item.id)}</code><small>${escapeHtml(item.name)}</small>`).join("") || "<small>No resource types selected</small>"}</div>
          </div>
          <p>${escapeHtml(generated.replacementPolicy)}</p>
        </section>
        <button class="ghost-btn wide" id="exportBtn" type="button"><i data-lucide="download"></i><span>Export handoff brief (JSON)</span></button>
      `;
    },
    attach: (root) => {
      root.querySelector("#exportBtn").addEventListener("click", exportBrief);
    },
  },
];

// ── Step UI helpers ──────────────────────────────────────────────────
function choiceTile(value, active, icon, title, sub) {
  return `
    <button class="choice${active ? " active" : ""}" type="button" data-choice="${escapeHtml(value)}">
      <i data-lucide="${icon}"></i>
      <strong>${escapeHtml(title)}</strong>
      <span>${escapeHtml(sub)}</span>
    </button>
  `;
}
function bindChoices(root, fn) {
  root.querySelectorAll("[data-choice]").forEach((b) =>
    b.addEventListener("click", () => fn(b.dataset.choice))
  );
}

// ── Item-attribute steps (one Model link per family) ─────────────────
function attributeExamplesFor(family) {
  const palette = (industryAttributePalette[state.industry] || []).filter((item) => item.f === family).map((item) => item.n);
  const seen = new Set(palette.map((name) => name.toLowerCase()));
  const extras = (familyBase[family] || []).filter((name) => !seen.has(name.toLowerCase()));
  return { palette, extras };
}
function attributeChip(family, name, active) {
  return `<button class="attr-chip${active ? " active" : ""}" type="button" data-attr-family="${escapeHtml(family)}" data-attr-name="${escapeHtml(name)}">${escapeHtml(name)}</button>`;
}
function attributeSlot(familyId) {
  if (!state.attr) state.attr = {};
  if (!state.attr[familyId]) state.attr[familyId] = { picks: [], confirmed: false };
  return state.attr[familyId];
}
function makeAttributeStep(concept) {
  return {
    id: `attr-${concept.id}`, phase: "Model", nav: concept.short,
    title: () => `What ${concept.name.toLowerCase()} does your ${itemTerm()} carry?`,
    sub: () => `In ${profile().badge} these are modeled as ${attributeProfile()[concept.dialectKey]}. Pick the ones that matter — pre-populated for ${industry()?.name || "your industry"} and kept representative until customer master data replaces them.`,
    hint: "Select the attributes that apply, or mark none, to continue.",
    gate: () => { const slot = attributeSlot(concept.id); return slot.picks.length > 0 || slot.confirmed; },
    body: () => {
      const slot = attributeSlot(concept.id);
      const { palette, extras } = attributeExamplesFor(concept.id);
      const ap = attributeProfile();
      const lens = concept.id === "quality" && qualityLens();
      return `
        <div class="industry-synthesis">
          <i data-lucide="${concept.icon}"></i>
          <div><strong>${escapeHtml(ap[concept.dialectKey])}</strong><p>${escapeHtml(concept.role)} ${escapeHtml(concept.aps)}</p></div>
          <span>${escapeHtml(profile().badge)} dialect</span>
        </div>
        ${palette.length ? `
          <p class="attr-suggested-label">${escapeHtml(industry()?.name || "Industry")} examples</p>
          <div class="attr-chips">${palette.map((name) => attributeChip(concept.id, name, slot.picks.includes(name))).join("")}</div>` : ""}
        <p class="attr-suggested-label">Common ${escapeHtml(profile().badge)} fields</p>
        <div class="attr-chips">
          ${extras.map((name) => attributeChip(concept.id, name, slot.picks.includes(name))).join("")}
          <button class="attr-chip none${slot.confirmed && slot.picks.length === 0 ? " active" : ""}" type="button" data-attr-none="${concept.id}"><i data-lucide="ban"></i>None apply</button>
        </div>
        ${lens ? `<p class="representative-note attribute-lens"><i data-lucide="microscope"></i> Regulated / process lens: <b>CQA</b> = what must be true of the product (e.g. dissolution rate); <b>CPP</b> = what must be controlled in the process (e.g. mixing speed, drying temperature). MES captures these as process parameters and electronic batch-record values.</p>` : ""}
        ${slot.picks.length ? `<p class="representative-note"><i data-lucide="check"></i> ${slot.picks.length} attribute${slot.picks.length === 1 ? "" : "s"} captured.</p>` : ""}
      `;
    },
    attach: (root) => {
      const slot = attributeSlot(concept.id);
      root.querySelectorAll("[data-attr-name]").forEach((button) => button.addEventListener("click", () => {
        const set = new Set(slot.picks);
        const name = button.dataset.attrName;
        set.has(name) ? set.delete(name) : set.add(name);
        slot.picks = [...set];
        slot.confirmed = true;
        render();
      }));
      root.querySelector(`[data-attr-none="${concept.id}"]`)?.addEventListener("click", () => {
        slot.picks = [];
        slot.confirmed = true;
        render();
      });
    },
  };
}

function scoreDemo(laneId) {
  let r;
  if (laneId === "wc-pack-2") r = { score: 92, note: "Packaging Line 2 is a valid alternate, and the model keeps the Line 3 calendar issue open for data cleanup." };
  else if (laneId === "wc-pack-3") r = { score: 54, note: "Line 3 still has an unresolved calendar issue — it shouldn't run the rush order." };
  else r = { score: 28, note: "That resource doesn't perform packaging operations. The miss links to training and role readiness." };
  state.demo = { laneId, ...r };
  render();
}
